version: '3.8'

services:
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: learning-rocks
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
